/* GENERATED by update-media.py - don't edit by hand, it gets overwritten.
   To change captions or order, edit captions.txt and run update-media.bat. */

window.MEDIA = {
  "categories": [
    {
      "id": "motion-3d",
      "label": "Motion + 3D",
      "items": [
        {
          "type": "video",
          "src": "media/motion+3d/clner.mp4",
          "caption": "logo for storage/logistics facility"
        },
        {
          "type": "video",
          "src": "media/motion+3d/morang.mp4",
          "caption": "visuals for a club event"
        },
        {
          "type": "video",
          "src": "media/motion+3d/20_jooIKqkplIe7YkDx6uSgPR5qLk.mp4",
          "caption": "???"
        },
        {
          "type": "video",
          "src": "media/motion+3d/22_g27zwTB3xokqe3GAieGJW47mPa0.mp4",
          "caption": "concept for swarowski"
        },
        {
          "type": "video",
          "src": "media/motion+3d/KULTIV%20visual_cut.mp4",
          "caption": "explaining b2b service value"
        },
        {
          "type": "video",
          "src": "media/motion+3d/worddem.mp4",
          "caption": "organizing letters"
        },
        {
          "type": "video",
          "src": "media/motion+3d/logins.mp4",
          "caption": "some login ideas"
        },
        {
          "type": "video",
          "src": "media/motion+3d/Screenrecorder-20261007-173124~2.mp4",
          "caption": "weather app"
        }
      ]
    },
    {
      "id": "products",
      "label": "Products",
      "items": [
        {
          "type": "image",
          "src": "media/products/a1.png",
          "caption": "light idea #1"
        },
        {
          "type": "image",
          "src": "media/products/a3.png",
          "caption": "light idea #2"
        },
        {
          "type": "video",
          "src": "media/products/cloxwa(2).mp4",
          "caption": "some clock design"
        },
        {
          "type": "video",
          "src": "media/products/exprelessgrai.mp4",
          "caption": "a snake train"
        },
        {
          "type": "video",
          "src": "media/products/light(1).mp4",
          "caption": "plant lighting"
        },
        {
          "type": "image",
          "src": "media/products/lights.png",
          "caption": "lighting"
        },
        {
          "type": "video",
          "src": "media/products/pg.mp4",
          "caption": "a slightly dangerous and therefore interesting playground"
        },
        {
          "type": "video",
          "src": "media/products/pos.mp4",
          "caption": "a watch"
        },
        {
          "type": "image",
          "src": "media/products/ren%202.png",
          "caption": "some table ware"
        },
        {
          "type": "video",
          "src": "media/products/schrnkx.mp4",
          "caption": "fancy cupboard"
        },
        {
          "type": "image",
          "src": "media/products/sofa.png",
          "caption": "sofa"
        },
        {
          "type": "image",
          "src": "media/products/stool(1).png",
          "caption": "chair"
        },
        {
          "type": "image",
          "src": "media/products/trevolte.png",
          "caption": "friendly surveillance camera design"
        }
      ]
    },
    {
      "id": "graphics-illustrations",
      "label": "Graphics + Illustrations",
      "items": [
        {
          "type": "video",
          "src": "media/graphics+illustrations/bikmo%20(online-video-cutter.com).mp4",
          "caption": "concept for bike insurance"
        },
        {
          "type": "image",
          "src": "media/graphics+illustrations/canren.png",
          "caption": "some can designs"
        },
        {
          "type": "image",
          "src": "media/graphics+illustrations/ud%20bww%20mix.png",
          "caption": "poster"
        },
        {
          "type": "video",
          "src": "media/graphics+illustrations/04_0N2XF0LZX0CF1voVonYWwl8I4Q.mp4",
          "caption": "o jogo bonito"
        },
        {
          "type": "image",
          "src": "media/graphics+illustrations/05_9xdlrandm3qIApgC39UNWyGh0.png",
          "caption": "cigarette packaging"
        },
        {
          "type": "image",
          "src": "media/graphics+illustrations/08_CDlS7l3O3af56v9QmEKvSVv8U.png",
          "caption": ""
        },
        {
          "type": "image",
          "src": "media/graphics+illustrations/16_jt8M4e2ibN4GmiwxoYlNP7X7RZA.png",
          "caption": "concept poster for the tour de luxembourg"
        },
        {
          "type": "image",
          "src": "media/graphics+illustrations/23_kbOVyAouzTgmkqmb1PXBBwo2g.png",
          "caption": "project logo for ses"
        }
      ]
    }
  ],
  "loaders": [
    "loading/ld%203dots.mp4",
    "loading/ld%204blu.mp4",
    "loading/ld%204nor.mp4",
    "loading/ld%204sb.mp4",
    "loading/ld%204sn.mp4",
    "loading/ld%20d12.mp4",
    "loading/ld%20d21.mp4"
  ]
};
